import 'dart:io';

import '../domain/entities/package_size.dart';
import '../utils/size_formatter.dart';

class HtmlReporter {
  void generate({
    required List<PackageSize> packages,
    required String outputPath,
  }) {
    final totalBytes = packages.fold<int>(0, (sum, e) => sum + e.bytes);

    final largest = packages.isEmpty ? null : packages.first;

    final rows = packages.map((package) {
      return '''
<tr>
<td>${package.packageName}</td>
<td>${formatSize(package.bytes)}</td>
<td>${package.percentage.toStringAsFixed(2)}%</td>
<td>
<div class="progress">
<div class="bar" style="width:${package.percentage}%;"></div>
</div>
</td>
</tr>
''';
    }).join();

    final html =
        '''
<!DOCTYPE html>
<html>
<head>

<meta charset="UTF-8">

<title>Flutter Package Size Report</title>

<style>

body{
font-family:Arial,sans-serif;
background:#f5f5f5;
padding:40px;
color:#222;
}

.container{
max-width:1100px;
margin:auto;
}

h1{
margin-bottom:10px;
}

.card{
background:white;
padding:20px;
border-radius:10px;
margin-bottom:20px;
box-shadow:0 2px 8px rgba(0,0,0,.08);
}

.summary{
display:flex;
gap:20px;
flex-wrap:wrap;
}

.summary-item{
flex:1;
min-width:220px;
background:#fafafa;
padding:20px;
border-radius:8px;
border:1px solid #ddd;
}

.summary-title{
font-size:14px;
color:#666;
margin-bottom:8px;
}

.summary-value{
font-size:24px;
font-weight:bold;
}

table{
width:100%;
border-collapse:collapse;
background:white;
}

th{
background:#1976d2;
color:white;
padding:12px;
text-align:left;
}

td{
padding:12px;
border-bottom:1px solid #eee;
}

tr:hover{
background:#fafafa;
}

.progress{
width:100%;
height:12px;
background:#ddd;
border-radius:10px;
overflow:hidden;
}

.bar{
height:100%;
background:#1976d2;
}

footer{
margin-top:30px;
font-size:13px;
color:#666;
text-align:center;
}

</style>

</head>

<body>

<div class="container">

<h1>📦 Flutter Package Size Report</h1>

<div class="card">

<div class="summary">

<div class="summary-item">
<div class="summary-title">Total Packages</div>
<div class="summary-value">${packages.length}</div>
</div>

<div class="summary-item">
<div class="summary-title">Total Size</div>
<div class="summary-value">${formatSize(totalBytes)}</div>
</div>

<div class="summary-item">
<div class="summary-title">Largest Package</div>
<div class="summary-value">${largest?.packageName ?? '-'}</div>
</div>

</div>

</div>

<table>

<thead>

<tr>
<th>Package</th>
<th>Size</th>
<th>Percent</th>
<th>Usage</th>
</tr>

</thead>

<tbody>

$rows

</tbody>

</table>

<footer>

Generated by flutter_package_size

</footer>

</div>

</body>

</html>
''';

    final file = File(outputPath);

    file.writeAsStringSync(html);

    print('');
    print('✅ HTML report generated');
    print(file.absolute.path);
  }
}
